name: Tectonic-on-arXiv
description: 'Runs tectonic against a corpus of arXiv papers'
inputs:
  head:
    description: 'The head commit to test'
    required: true
  base:
    description: 'The base commit to test against'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.head }}
    - ${{ inputs.base }}
