services:
  app:
    build: .
    #user: ${UID}
    volumes:
      - ./datasets:/github/workspace/datasets:ro
      - ./reports:/github/workspace/reports:rw
      - USERS_TECTONIC_DIR:/github/workspace:rw
      - ./ci-tex-cache:/root/.cache/Tectonic:rw
      - ./ci-cargo-cache/git:/root/.cargo/git:rw
      - ./ci-cargo-cache/registry:/root/.cargo/registry:rw
      - ./ci-cargo-cache/CACHEDIR.TAG:/root/.cargo/CACHEDIR.TAG:rw
